# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
    ]
